/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Nueva_Factura_Compra extends javax.swing.JFrame {

    /**
     * Creates new form Nueva_Factura_Compra
     */
    public Nueva_Factura_Compra() {
        initComponents();
    }

    public JButton getBtncancelarfactcomp() {
        return btncancelarfactcomp;
    }

    public void setBtncancelarfactcomp(JButton btncancelarfactcomp) {
        this.btncancelarfactcomp = btncancelarfactcomp;
    }

    public JButton getBtnguardarfactcomp() {
        return btnguardarfactcomp;
    }

    public void setBtnguardarfactcomp(JButton btnguardarfactcomp) {
        this.btnguardarfactcomp = btnguardarfactcomp;
    }

    public JComboBox<String> getCmbtipopagofactcompa() {
        return cmbtipopagofactcompa;
    }

    public void setCmbtipopagofactcompa(JComboBox<String> cmbtipopagofactcompa) {
        this.cmbtipopagofactcompa = cmbtipopagofactcompa;
    }

    public JPanel getPanelFacturacompra() {
        return panelFacturacompra;
    }

    public void setPanelFacturacompra(JPanel panelFacturacompra) {
        this.panelFacturacompra = panelFacturacompra;
    }

    public JTextField getTxtidentiprovefact() {
        return txtidentiprovefact;
    }

    public void setTxtidentiprovefact(JTextField txtidentiprovefact) {
        this.txtidentiprovefact = txtidentiprovefact;
    }

    public JTextField getTxtidentiusufactcomp() {
        return txtidentiusufactcomp;
    }

    public void setTxtidentiusufactcomp(JTextField txtidentiusufactcomp) {
        this.txtidentiusufactcomp = txtidentiusufactcomp;
    }

    public JButton getBtnbuscarproveedor() {
        return btnbuscarproveedor;
    }

    public void setBtnbuscarproveedor(JButton btnbuscarproveedor) {
        this.btnbuscarproveedor = btnbuscarproveedor;
    }

    public JButton getBtnbuscarusuario() {
        return btnbuscarusuario;
    }

    public void setBtnbuscarusuario(JButton btnbuscarusuario) {
        this.btnbuscarusuario = btnbuscarusuario;
    }

    public JTextField getTxtnumerodecomprobante() {
        return txtnumerodecomprobante;
    }

    public void setTxtnumerodecomprobante(JTextField txtnumerodecomprobante) {
        this.txtnumerodecomprobante = txtnumerodecomprobante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFacturacompra = new javax.swing.JPanel();
        lblidentiproveedor = new javax.swing.JLabel();
        lblidentiusu = new javax.swing.JLabel();
        lbltipopagofactcomp = new javax.swing.JLabel();
        btnguardarfactcomp = new javax.swing.JButton();
        btncancelarfactcomp = new javax.swing.JButton();
        txtidentiprovefact = new javax.swing.JTextField();
        txtidentiusufactcomp = new javax.swing.JTextField();
        cmbtipopagofactcompa = new javax.swing.JComboBox<>();
        btnbuscarproveedor = new javax.swing.JButton();
        btnbuscarusuario = new javax.swing.JButton();
        lblidentiusu1 = new javax.swing.JLabel();
        txtnumerodecomprobante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFacturacompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Factura Compra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        lblidentiproveedor.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblidentiproveedor.setForeground(new java.awt.Color(0, 153, 153));
        lblidentiproveedor.setText("Identificación Proveedor");

        lblidentiusu.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblidentiusu.setForeground(new java.awt.Color(0, 153, 153));
        lblidentiusu.setText("Identificación Usuario");

        lbltipopagofactcomp.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbltipopagofactcomp.setForeground(new java.awt.Color(0, 153, 153));
        lbltipopagofactcomp.setText("Tipo de Pago");

        btnguardarfactcomp.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnguardarfactcomp.setForeground(new java.awt.Color(0, 153, 153));
        btnguardarfactcomp.setText("Guardar");

        btncancelarfactcomp.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btncancelarfactcomp.setForeground(new java.awt.Color(0, 153, 153));
        btncancelarfactcomp.setText("Cancelar");

        txtidentiprovefact.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        txtidentiusufactcomp.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        cmbtipopagofactcompa.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbtipopagofactcompa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "PSE", "Tarjeta de Débito", "Tarjeta de Crédito", "Efectivo" }));

        btnbuscarproveedor.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnbuscarproveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N

        btnbuscarusuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnbuscarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N

        lblidentiusu1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblidentiusu1.setForeground(new java.awt.Color(0, 153, 153));
        lblidentiusu1.setText("N° Comprobante");

        txtnumerodecomprobante.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelFacturacompraLayout = new javax.swing.GroupLayout(panelFacturacompra);
        panelFacturacompra.setLayout(panelFacturacompraLayout);
        panelFacturacompraLayout.setHorizontalGroup(
            panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFacturacompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnguardarfactcomp)
                .addGap(52, 52, 52)
                .addComponent(btncancelarfactcomp)
                .addGap(124, 124, 124))
            .addGroup(panelFacturacompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblidentiproveedor)
                    .addComponent(lblidentiusu)
                    .addComponent(lbltipopagofactcomp)
                    .addComponent(lblidentiusu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtidentiusufactcomp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidentiprovefact, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(cmbtipopagofactcompa, 0, 239, Short.MAX_VALUE)
                    .addComponent(txtnumerodecomprobante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscarproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFacturacompraLayout.setVerticalGroup(
            panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturacompraLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidentiproveedor)
                    .addComponent(txtidentiprovefact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarproveedor))
                .addGap(18, 18, 18)
                .addGroup(panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidentiusu)
                    .addComponent(txtidentiusufactcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidentiusu1)
                    .addComponent(txtnumerodecomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltipopagofactcomp)
                    .addComponent(cmbtipopagofactcompa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelFacturacompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardarfactcomp)
                    .addComponent(btncancelarfactcomp))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFacturacompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelFacturacompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarproveedor;
    private javax.swing.JButton btnbuscarusuario;
    private javax.swing.JButton btncancelarfactcomp;
    private javax.swing.JButton btnguardarfactcomp;
    private javax.swing.JComboBox<String> cmbtipopagofactcompa;
    private javax.swing.JLabel lblidentiproveedor;
    private javax.swing.JLabel lblidentiusu;
    private javax.swing.JLabel lblidentiusu1;
    private javax.swing.JLabel lbltipopagofactcomp;
    private javax.swing.JPanel panelFacturacompra;
    private javax.swing.JTextField txtidentiprovefact;
    private javax.swing.JTextField txtidentiusufactcomp;
    private javax.swing.JTextField txtnumerodecomprobante;
    // End of variables declaration//GEN-END:variables
}
