/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Principal() {
        initComponents();
    }

    public JButton getBtnnuevo() {
        return btnnuevo;
    }

    public void setBtnnuevo(JButton btnnuevo) {
        this.btnnuevo = btnnuevo;
    }

    public JButton getBtnnueclien() {
        return btnnueclien;
    }

    public void setBtnnueclien(JButton btnnueclien) {
        this.btnnueclien = btnnueclien;
    }

    public JButton getBtnnuevoprovee() {
        return btnnuevoprovee;
    }

    public void setBtnnuevoprovee(JButton btnnuevoprovee) {
        this.btnnuevoprovee = btnnuevoprovee;
    }

    public JTable getJtcliente() {
        return jtcliente;
    }

    public void setJtcliente(JTable jtcliente) {
        this.jtcliente = jtcliente;
    }

    public JTextField getJtfcliente() {
        return jtfcliente;
    }

    public void setJtfcliente(JTextField jtfcliente) {
        this.jtfcliente = jtfcliente;
    }

    public JTextField getJtfprovee() {
        return jtfprovee;
    }

    public void setJtfprovee(JTextField jtfprovee) {
        this.jtfprovee = jtfprovee;
    }

    public JTextField getJtfusuario() {
        return jtfusuario;
    }

    public void setJtfusuario(JTextField jtfusuario) {
        this.jtfusuario = jtfusuario;
    }

    public JTable getJtprovee() {
        return jtprovee;
    }

    public void setJtprovee(JTable jtprovee) {
        this.jtprovee = jtprovee;
    }

    public JTable getJtusuario() {
        return jtusuario;
    }

    public void setJtusuario(JTable jtusuario) {
        this.jtusuario = jtusuario;
    }

    public JTabbedPane getTpPrincipal() {
        return tpPrincipal;
    }

    public void setTpPrincipal(JTabbedPane tpPrincipal) {
        this.tpPrincipal = tpPrincipal;
    }

    public JButton getBtnnuevaFactura() {
        return btnnuevaFactura;
    }

    public void setBtnnuevaFactura(JButton btnnuevaFactura) {
        this.btnnuevaFactura = btnnuevaFactura;
    }

    public JButton getBtnnuevaVenta() {
        return btnnuevaVenta;
    }

    public void setBtnnuevaVenta(JButton btnnuevaVenta) {
        this.btnnuevaVenta = btnnuevaVenta;
    }

    public JButton getBtnnuevoproducto() {
        return btnnuevoproducto;
    }

    public void setBtnnuevoproducto(JButton btnnuevoproducto) {
        this.btnnuevoproducto = btnnuevoproducto;
    }

    public JTable getTablaProducto() {
        return tablaProducto;
    }

    public void setTablaProducto(JTable tablaProducto) {
        this.tablaProducto = tablaProducto;
    }

    public JTable getTablafactura() {
        return tablafactura;
    }

    public void setTablafactura(JTable tablafactura) {
        this.tablafactura = tablafactura;
    }

    public JTable getTablaventa() {
        return tablaventa;
    }

    public void setTablaventa(JTable tablaventa) {
        this.tablaventa = tablaventa;
    }

    public JTextField getTxtbuscarfactura() {
        return txtbuscarfactura;
    }

    public void setTxtbuscarfactura(JTextField txtbuscarfactura) {
        this.txtbuscarfactura = txtbuscarfactura;
    }

    public JTextField getTxtbuscarproduct() {
        return txtbuscarproduct;
    }

    public void setTxtbuscarproduct(JTextField txtbuscarproduct) {
        this.txtbuscarproduct = txtbuscarproduct;
    }

    public JTextField getTxtbuscarventa() {
        return txtbuscarventa;
    }

    public void setTxtbuscarventa(JTextField txtbuscarventa) {
        this.txtbuscarventa = txtbuscarventa;
    }
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpPrincipal = new javax.swing.JTabbedPane();
        jpusuario = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtusuario = new javax.swing.JTable();
        jtfusuario = new javax.swing.JTextField();
        jpcliente = new javax.swing.JPanel();
        btnnueclien = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtcliente = new javax.swing.JTable();
        jtfcliente = new javax.swing.JTextField();
        jpproveedor = new javax.swing.JPanel();
        btnnuevoprovee = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtprovee = new javax.swing.JTable();
        jtfprovee = new javax.swing.JTextField();
        jpproducto = new javax.swing.JPanel();
        btnnuevoproducto = new javax.swing.JButton();
        txtbuscarproduct = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jpfactura = new javax.swing.JPanel();
        btnnuevaFactura = new javax.swing.JButton();
        txtbuscarfactura = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablafactura = new javax.swing.JTable();
        jpVenta = new javax.swing.JPanel();
        btnnuevaVenta = new javax.swing.JButton();
        txtbuscarventa = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaventa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIENDA.COM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 48), new java.awt.Color(0, 153, 153))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        tpPrincipal.setForeground(new java.awt.Color(0, 153, 153));
        tpPrincipal.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N

        btnnuevo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(0, 153, 153));
        btnnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\Tienda_Com\\src\\main\\resources\\img\\usuario.png")); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtusuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jtusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtusuario);

        jtfusuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jtfusuario.setForeground(new java.awt.Color(204, 204, 204));
        jtfusuario.setText("Buscar Usuario");
        jtfusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfusuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpusuarioLayout = new javax.swing.GroupLayout(jpusuario);
        jpusuario.setLayout(jpusuarioLayout);
        jpusuarioLayout.setHorizontalGroup(
            jpusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpusuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                    .addGroup(jpusuarioLayout.createSequentialGroup()
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jpusuarioLayout.setVerticalGroup(
            jpusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpusuarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );

        tpPrincipal.addTab("Usuario", jpusuario);

        btnnueclien.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnnueclien.setForeground(new java.awt.Color(0, 153, 153));
        btnnueclien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btnnueclien.setText("Nuevo");
        btnnueclien.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtcliente.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jtcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtcliente);

        jtfcliente.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jtfcliente.setForeground(new java.awt.Color(204, 204, 204));
        jtfcliente.setText("Buscar Cliente");

        javax.swing.GroupLayout jpclienteLayout = new javax.swing.GroupLayout(jpcliente);
        jpcliente.setLayout(jpclienteLayout);
        jpclienteLayout.setHorizontalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                    .addGroup(jpclienteLayout.createSequentialGroup()
                        .addComponent(btnnueclien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jpclienteLayout.setVerticalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnueclien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpPrincipal.addTab("Cliente", jpcliente);

        btnnuevoprovee.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnnuevoprovee.setForeground(new java.awt.Color(0, 153, 153));
        btnnuevoprovee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btnnuevoprovee.setText("Nuevo");
        btnnuevoprovee.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtprovee.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jtprovee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtprovee);

        jtfprovee.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jtfprovee.setForeground(new java.awt.Color(204, 204, 204));
        jtfprovee.setText("Buscar Proveedor");

        javax.swing.GroupLayout jpproveedorLayout = new javax.swing.GroupLayout(jpproveedor);
        jpproveedor.setLayout(jpproveedorLayout);
        jpproveedorLayout.setHorizontalGroup(
            jpproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpproveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                    .addGroup(jpproveedorLayout.createSequentialGroup()
                        .addComponent(btnnuevoprovee, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfprovee, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jpproveedorLayout.setVerticalGroup(
            jpproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpproveedorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfprovee)
                    .addComponent(btnnuevoprovee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpPrincipal.addTab("Proveedor", jpproveedor);

        btnnuevoproducto.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnnuevoproducto.setForeground(new java.awt.Color(0, 153, 153));
        btnnuevoproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btnnuevoproducto.setText("Nuevo");

        txtbuscarproduct.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtbuscarproduct.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscarproduct.setText("Buscar Producto");

        tablaProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tablaProducto);

        javax.swing.GroupLayout jpproductoLayout = new javax.swing.GroupLayout(jpproducto);
        jpproducto.setLayout(jpproductoLayout);
        jpproductoLayout.setHorizontalGroup(
            jpproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpproductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                    .addGroup(jpproductoLayout.createSequentialGroup()
                        .addComponent(btnnuevoproducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscarproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpproductoLayout.setVerticalGroup(
            jpproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpproductoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevoproducto)
                    .addComponent(txtbuscarproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpPrincipal.addTab("Producto", jpproducto);

        btnnuevaFactura.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnnuevaFactura.setForeground(new java.awt.Color(0, 153, 153));
        btnnuevaFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btnnuevaFactura.setText("Nueva");

        txtbuscarfactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtbuscarfactura.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscarfactura.setText("Buscar Factura");

        tablafactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tablafactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tablafactura);

        javax.swing.GroupLayout jpfacturaLayout = new javax.swing.GroupLayout(jpfactura);
        jpfactura.setLayout(jpfacturaLayout);
        jpfacturaLayout.setHorizontalGroup(
            jpfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                    .addGroup(jpfacturaLayout.createSequentialGroup()
                        .addComponent(btnnuevaFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jpfacturaLayout.setVerticalGroup(
            jpfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfacturaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevaFactura)
                    .addComponent(txtbuscarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpPrincipal.addTab("Factura", jpfactura);

        btnnuevaVenta.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnnuevaVenta.setForeground(new java.awt.Color(0, 153, 153));
        btnnuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btnnuevaVenta.setText("Nueva");

        txtbuscarventa.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtbuscarventa.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscarventa.setText("Buscar Venta");

        tablaventa.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tablaventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tablaventa);

        javax.swing.GroupLayout jpVentaLayout = new javax.swing.GroupLayout(jpVenta);
        jpVenta.setLayout(jpVentaLayout);
        jpVentaLayout.setHorizontalGroup(
            jpVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                    .addGroup(jpVentaLayout.createSequentialGroup()
                        .addComponent(btnnuevaVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscarventa, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpVentaLayout.setVerticalGroup(
            jpVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVentaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevaVenta)
                    .addComponent(txtbuscarventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpPrincipal.addTab("Venta", jpVenta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpPrincipal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 361, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfusuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnueclien;
    private javax.swing.JButton btnnuevaFactura;
    private javax.swing.JButton btnnuevaVenta;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnnuevoproducto;
    private javax.swing.JButton btnnuevoprovee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel jpVenta;
    private javax.swing.JPanel jpcliente;
    private javax.swing.JPanel jpfactura;
    private javax.swing.JPanel jpproducto;
    private javax.swing.JPanel jpproveedor;
    private javax.swing.JPanel jpusuario;
    private javax.swing.JTable jtcliente;
    private javax.swing.JTextField jtfcliente;
    private javax.swing.JTextField jtfprovee;
    private javax.swing.JTextField jtfusuario;
    private javax.swing.JTable jtprovee;
    private javax.swing.JTable jtusuario;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTable tablafactura;
    private javax.swing.JTable tablaventa;
    private javax.swing.JTabbedPane tpPrincipal;
    private javax.swing.JTextField txtbuscarfactura;
    private javax.swing.JTextField txtbuscarproduct;
    private javax.swing.JTextField txtbuscarventa;
    // End of variables declaration//GEN-END:variables
}
