/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Buscar_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Buscar_Cliente
     */
    public Buscar_Cliente() {
        initComponents();
    }

    public JPanel getJPanelbucarcliente() {
        return JPanelbucarcliente;
    }

    public void setJPanelbucarcliente(JPanel JPanelbucarcliente) {
        this.JPanelbucarcliente = JPanelbucarcliente;
    }

    public JTable getJTablaBuscarcliente() {
        return JTablaBuscarcliente;
    }

    public void setJTablaBuscarcliente(JTable JTablaBuscarcliente) {
        this.JTablaBuscarcliente = JTablaBuscarcliente;
    }

    public JTextField getTxtbuscarcliente() {
        return txtbuscarcliente;
    }

    public void setTxtbuscarcliente(JTextField txtbuscarcliente) {
        this.txtbuscarcliente = txtbuscarcliente;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelbucarcliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaBuscarcliente = new javax.swing.JTable();
        txtbuscarcliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelbucarcliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        JTablaBuscarcliente.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        JTablaBuscarcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTablaBuscarcliente);

        txtbuscarcliente.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtbuscarcliente.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscarcliente.setText("Buscar Cliente");

        javax.swing.GroupLayout JPanelbucarclienteLayout = new javax.swing.GroupLayout(JPanelbucarcliente);
        JPanelbucarcliente.setLayout(JPanelbucarclienteLayout);
        JPanelbucarclienteLayout.setHorizontalGroup(
            JPanelbucarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelbucarclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelbucarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelbucarclienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JPanelbucarclienteLayout.setVerticalGroup(
            JPanelbucarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelbucarclienteLayout.createSequentialGroup()
                .addComponent(txtbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelbucarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelbucarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelbucarcliente;
    private javax.swing.JTable JTablaBuscarcliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbuscarcliente;
    // End of variables declaration//GEN-END:variables
}
