/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Buscar_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Buscar_Producto
     */
    public Buscar_Producto() {
        initComponents();
    }

    public JPanel getJPanelbucarproducto() {
        return JPanelbucarproducto;
    }

    public void setJPanelbucarproducto(JPanel JPanelbucarproducto) {
        this.JPanelbucarproducto = JPanelbucarproducto;
    }

    public JTable getJTablaBuscarproducto() {
        return JTablaBuscarproducto;
    }

    public void setJTablaBuscarproducto(JTable JTablaBuscarproducto) {
        this.JTablaBuscarproducto = JTablaBuscarproducto;
    }

    public JTextField getTxtbuscarproducto() {
        return txtbuscarproducto;
    }

    public void setTxtbuscarproducto(JTextField txtbuscarproducto) {
        this.txtbuscarproducto = txtbuscarproducto;
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelbucarproducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaBuscarproducto = new javax.swing.JTable();
        txtbuscarproducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelbucarproducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        JTablaBuscarproducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        JTablaBuscarproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTablaBuscarproducto);

        txtbuscarproducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtbuscarproducto.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscarproducto.setText("Buscar Producto");

        javax.swing.GroupLayout JPanelbucarproductoLayout = new javax.swing.GroupLayout(JPanelbucarproducto);
        JPanelbucarproducto.setLayout(JPanelbucarproductoLayout);
        JPanelbucarproductoLayout.setHorizontalGroup(
            JPanelbucarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelbucarproductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelbucarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addGroup(JPanelbucarproductoLayout.createSequentialGroup()
                        .addComponent(txtbuscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPanelbucarproductoLayout.setVerticalGroup(
            JPanelbucarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelbucarproductoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtbuscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelbucarproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelbucarproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelbucarproducto;
    private javax.swing.JTable JTablaBuscarproducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbuscarproducto;
    // End of variables declaration//GEN-END:variables
}
